version: '3'
services:
  backend:
    build:
      context: ./api
      dockerfile: ./XlsFilterService/Dockerfile
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.client
    ports:
      - 80:80
